### ISSUE TITLE
Feedback Milestone 1

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI-532-wine-data#5]
* The goal/purpose of the app is not super clear in the overview section. Additionally, you didn’t define a target audience or potential users for it. I understood it better from the scenario you described. 
* In the description of the data set you don’t say where the data came from. Also, are you using all observations?
* Nice scenario description.
* Your app seems very interesting, the features you are proposing seem really cool. Improve visuals for future assignments (the table is kind of blurry).
* Maybe choose a slider for the year instead of a dropdown?
* Also, what is the world map selection for? Would it work in data view?

**Comment by sreyaguha** [comment]
Feedback taken into account and the proposal has been updated accordingly.
